name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: true
        fetch-depth: 0

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        sudo apt update -y && sudo apt install -y imagemagick
    - name: Run simulation
      run: |
        python karate_club.py
        ls -l
        git add -A
    - uses: actions/checkout@v3
      name: Commit files
    - run: |
        git config --local user.email "jakub@korsak.xyz"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "[bot] update animation.gif"
        git push
